version: "3.8"
services:
  weather-widget:
    platform: linux/amd64
    build: .
    image: weather-widget
    container_name: weather-widget
    working_dir: /app
    ports:
      - 3000:3000
      - 3333:3333
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh ./entrypoint.sh

networks:
  default:
    driver: bridge
